name: CI

on:
  workflow_dispatch:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-pip:
    name: Train and Save the model
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4